// Mock data for Employee Performance Monitoring
// This will be replaced with real API calls later

import type { Employee, Task, EmployeeChatMessage, PerformanceNotification } from '../../types/performance';

// Helper to generate timestamps
const now = Date.now();
const day = 24 * 60 * 60 * 1000;
const hour = 60 * 60 * 1000;

// Mock Employees - 10 employees across different departments
export const mockEmployees: Employee[] = [
  {
    id: 'emp-001',
    name: 'John Smith',
    email: 'john.smith@company.com',
    department: 'Development',
    role: 'Frontend Developer',
  },
  {
    id: 'emp-002',
    name: 'Sarah Johnson',
    email: 'sarah.johnson@company.com',
    department: 'Development',
    role: 'Backend Developer',
  },
  {
    id: 'emp-003',
    name: 'Mike Wilson',
    email: 'mike.wilson@company.com',
    department: 'Design',
    role: 'UI/UX Designer',
  },
  {
    id: 'emp-004',
    name: 'Emily Davis',
    email: 'emily.davis@company.com',
    department: 'Development',
    role: 'Full Stack Developer',
  },
  {
    id: 'emp-005',
    name: 'Alex Brown',
    email: 'alex.brown@company.com',
    department: 'QA',
    role: 'QA Engineer',
  },
  {
    id: 'emp-006',
    name: 'Jessica Martinez',
    email: 'jessica.martinez@company.com',
    department: 'Development',
    role: 'DevOps Engineer',
  },
  {
    id: 'emp-007',
    name: 'David Lee',
    email: 'david.lee@company.com',
    department: 'Development',
    role: 'Mobile Developer',
  },
  {
    id: 'emp-008',
    name: 'Amanda Taylor',
    email: 'amanda.taylor@company.com',
    department: 'Design',
    role: 'Graphic Designer',
  },
  {
    id: 'emp-009',
    name: 'Chris Anderson',
    email: 'chris.anderson@company.com',
    department: 'Development',
    role: 'Backend Developer',
  },
  {
    id: 'emp-010',
    name: 'Rachel White',
    email: 'rachel.white@company.com',
    department: 'QA',
    role: 'QA Lead',
  },
];

// Mock Tasks - Spread across 30 days for better date filtering testing
// Days 1-7: Recent tasks (7 days filter)
// Days 8-14: Medium-term tasks (14 days filter)
// Days 15-30: Older tasks (30 days filter)
export const mockTasks: Task[] = [
  // ============ LAST 7 DAYS (Days 1-7) ============
  // John Smith - Recent
  {
    id: 'task-001',
    title: 'Fix navigation bug',
    description: 'Navigation menu not closing on mobile',
    assignedTo: 'emp-001',
    assignedBy: 'manager-001',
    deadline: now + 1 * day,
    status: 'in_progress',
    estimatedHours: 4,
    priority: 'high',
    tags: ['bug', 'mobile'],
    createdAt: now - 2 * day,
    updatedAt: now - 1 * day,
  },
  {
    id: 'task-002',
    title: 'Update dashboard UI',
    description: 'Implement new card design',
    assignedTo: 'emp-001',
    assignedBy: 'manager-001',
    deadline: now - 1 * day,
    completedAt: now - 1 * day,
    status: 'completed',
    estimatedHours: 8,
    actualHours: 6,
    priority: 'medium',
    tags: ['ui', 'dashboard'],
    createdAt: now - 5 * day,
    updatedAt: now - 1 * day,
  },
  // Sarah Johnson - Recent (slacker pattern)
  {
    id: 'task-003',
    title: 'API endpoint optimization',
    description: 'Reduce response time for user queries',
    assignedTo: 'emp-002',
    assignedBy: 'manager-001',
    deadline: now - 2 * day,
    status: 'overdue',
    estimatedHours: 12,
    priority: 'high',
    tags: ['api', 'performance'],
    createdAt: now - 6 * day,
    updatedAt: now - 3 * day,
  },
  // Mike Wilson - Recent
  {
    id: 'task-004',
    title: 'Create homepage mockup',
    description: 'New landing page design',
    assignedTo: 'emp-003',
    assignedBy: 'manager-002',
    deadline: now + 2 * day,
    status: 'in_progress',
    estimatedHours: 16,
    priority: 'medium',
    tags: ['design', 'landing'],
    createdAt: now - 3 * day,
    updatedAt: now - 1 * day,
  },
  // Emily Davis - Recent (excellent)
  {
    id: 'task-005',
    title: 'Implement caching layer',
    description: 'Add Redis caching for API responses',
    assignedTo: 'emp-004',
    assignedBy: 'manager-001',
    deadline: now - 1 * day,
    completedAt: now - 2 * day,
    status: 'completed',
    estimatedHours: 20,
    actualHours: 16,
    priority: 'high',
    tags: ['backend', 'performance'],
    createdAt: now - 6 * day,
    updatedAt: now - 2 * day,
  },
  {
    id: 'task-006',
    title: 'Code review for payment module',
    description: 'Review PR #234',
    assignedTo: 'emp-004',
    assignedBy: 'manager-001',
    deadline: now,
    completedAt: now - 1 * day,
    status: 'completed',
    estimatedHours: 4,
    actualHours: 3,
    priority: 'medium',
    tags: ['review'],
    createdAt: now - 3 * day,
    updatedAt: now - 1 * day,
  },
  // Alex Brown - Recent (poor performer)
  {
    id: 'task-007',
    title: 'Write unit tests for auth',
    description: 'Achieve 80% coverage',
    assignedTo: 'emp-005',
    assignedBy: 'manager-001',
    deadline: now - 3 * day,
    status: 'overdue',
    estimatedHours: 8,
    priority: 'high',
    tags: ['testing', 'auth'],
    createdAt: now - 7 * day,
    updatedAt: now - 4 * day,
  },
  // Jessica Martinez - Recent
  {
    id: 'task-008',
    title: 'Deploy staging environment',
    description: 'Setup new staging server',
    assignedTo: 'emp-006',
    assignedBy: 'manager-001',
    deadline: now - 1 * day,
    completedAt: now - 1 * day,
    status: 'completed',
    estimatedHours: 6,
    actualHours: 5,
    priority: 'high',
    tags: ['devops', 'deployment'],
    createdAt: now - 4 * day,
    updatedAt: now - 1 * day,
  },
  // David Lee - Recent
  {
    id: 'task-009',
    title: 'Fix iOS crash on login',
    description: 'App crashes on iPhone 12',
    assignedTo: 'emp-007',
    assignedBy: 'manager-001',
    deadline: now - 1 * day,
    status: 'overdue',
    estimatedHours: 8,
    priority: 'urgent',
    tags: ['mobile', 'bug', 'ios'],
    createdAt: now - 5 * day,
    updatedAt: now - 2 * day,
  },
  // Amanda Taylor - Recent
  {
    id: 'task-010',
    title: 'Design email templates',
    description: 'Create 5 email templates',
    assignedTo: 'emp-008',
    assignedBy: 'manager-002',
    deadline: now + 1 * day,
    status: 'in_progress',
    estimatedHours: 10,
    priority: 'medium',
    tags: ['design', 'email'],
    createdAt: now - 2 * day,
    updatedAt: now - 1 * day,
  },
  // Rachel White - Recent
  {
    id: 'task-011',
    title: 'Security audit report',
    description: 'Complete Q4 security review',
    assignedTo: 'emp-010',
    assignedBy: 'manager-001',
    deadline: now,
    completedAt: now - 1 * day,
    status: 'completed',
    estimatedHours: 16,
    actualHours: 14,
    priority: 'high',
    tags: ['security', 'audit'],
    createdAt: now - 6 * day,
    updatedAt: now - 1 * day,
  },

  // ============ DAYS 8-14 (14 days filter) ============
  // John Smith
  {
    id: 'task-012',
    title: 'Implement dark mode',
    description: 'Add theme switching support',
    assignedTo: 'emp-001',
    assignedBy: 'manager-001',
    deadline: now - 8 * day,
    completedAt: now - 9 * day,
    status: 'completed',
    estimatedHours: 12,
    actualHours: 10,
    priority: 'medium',
    tags: ['ui', 'theme'],
    createdAt: now - 12 * day,
    updatedAt: now - 9 * day,
  },
  {
    id: 'task-013',
    title: 'Refactor form components',
    description: 'Extract reusable form components',
    assignedTo: 'emp-001',
    assignedBy: 'manager-001',
    deadline: now - 10 * day,
    completedAt: now - 11 * day,
    status: 'completed',
    estimatedHours: 8,
    actualHours: 7,
    priority: 'low',
    tags: ['refactor', 'components'],
    createdAt: now - 14 * day,
    updatedAt: now - 11 * day,
  },
  // Sarah Johnson - More delays
  {
    id: 'task-014',
    title: 'Database migration script',
    description: 'Migrate user table schema',
    assignedTo: 'emp-002',
    assignedBy: 'manager-001',
    deadline: now - 12 * day,
    completedAt: now - 9 * day,
    status: 'completed',
    estimatedHours: 6,
    actualHours: 18,
    priority: 'high',
    tags: ['database', 'migration'],
    createdAt: now - 14 * day,
    updatedAt: now - 9 * day,
  },
  {
    id: 'task-015',
    title: 'Fix memory leak in worker',
    description: 'Background job consuming too much memory',
    assignedTo: 'emp-002',
    assignedBy: 'manager-001',
    deadline: now - 9 * day,
    status: 'overdue',
    estimatedHours: 8,
    priority: 'urgent',
    tags: ['bug', 'performance'],
    createdAt: now - 13 * day,
    updatedAt: now - 10 * day,
  },
  // Mike Wilson
  {
    id: 'task-016',
    title: 'Mobile app icons',
    description: 'Create app icon set for iOS and Android',
    assignedTo: 'emp-003',
    assignedBy: 'manager-002',
    deadline: now - 8 * day,
    completedAt: now - 8 * day,
    status: 'completed',
    estimatedHours: 8,
    actualHours: 10,
    priority: 'medium',
    tags: ['design', 'mobile'],
    createdAt: now - 12 * day,
    updatedAt: now - 8 * day,
  },
  {
    id: 'task-017',
    title: 'Update brand guidelines',
    description: 'Refresh color palette documentation',
    assignedTo: 'emp-003',
    assignedBy: 'manager-002',
    deadline: now - 10 * day,
    completedAt: now - 11 * day,
    status: 'completed',
    estimatedHours: 12,
    actualHours: 11,
    priority: 'low',
    tags: ['design', 'documentation'],
    createdAt: now - 14 * day,
    updatedAt: now - 11 * day,
  },
  // Emily Davis
  {
    id: 'task-018',
    title: 'Build notification system',
    description: 'Real-time notifications via WebSocket',
    assignedTo: 'emp-004',
    assignedBy: 'manager-001',
    deadline: now - 9 * day,
    completedAt: now - 10 * day,
    status: 'completed',
    estimatedHours: 24,
    actualHours: 20,
    priority: 'high',
    tags: ['backend', 'websocket'],
    createdAt: now - 14 * day,
    updatedAt: now - 10 * day,
  },
  // Alex Brown
  {
    id: 'task-019',
    title: 'Setup test automation',
    description: 'Configure CI/CD pipeline for tests',
    assignedTo: 'emp-005',
    assignedBy: 'manager-001',
    deadline: now - 10 * day,
    status: 'overdue',
    estimatedHours: 12,
    priority: 'medium',
    tags: ['testing', 'ci-cd'],
    createdAt: now - 14 * day,
    updatedAt: now - 11 * day,
  },
  // Jessica Martinez
  {
    id: 'task-020',
    title: 'Kubernetes cluster setup',
    description: 'Production K8s environment',
    assignedTo: 'emp-006',
    assignedBy: 'manager-001',
    deadline: now - 8 * day,
    completedAt: now - 9 * day,
    status: 'completed',
    estimatedHours: 20,
    actualHours: 18,
    priority: 'high',
    tags: ['devops', 'kubernetes'],
    createdAt: now - 13 * day,
    updatedAt: now - 9 * day,
  },
  {
    id: 'task-021',
    title: 'Setup monitoring alerts',
    description: 'Configure PagerDuty integration',
    assignedTo: 'emp-006',
    assignedBy: 'manager-001',
    deadline: now - 11 * day,
    completedAt: now - 12 * day,
    status: 'completed',
    estimatedHours: 6,
    actualHours: 5,
    priority: 'medium',
    tags: ['devops', 'monitoring'],
    createdAt: now - 14 * day,
    updatedAt: now - 12 * day,
  },
  // David Lee
  {
    id: 'task-022',
    title: 'Android push notifications',
    description: 'Implement FCM integration',
    assignedTo: 'emp-007',
    assignedBy: 'manager-001',
    deadline: now - 9 * day,
    completedAt: now - 10 * day,
    status: 'completed',
    estimatedHours: 12,
    actualHours: 14,
    priority: 'high',
    tags: ['mobile', 'android'],
    createdAt: now - 14 * day,
    updatedAt: now - 10 * day,
  },
  // Amanda Taylor
  {
    id: 'task-023',
    title: 'Marketing banner set',
    description: 'Create 10 banner variations',
    assignedTo: 'emp-008',
    assignedBy: 'manager-002',
    deadline: now - 10 * day,
    completedAt: now - 11 * day,
    status: 'completed',
    estimatedHours: 8,
    actualHours: 7,
    priority: 'medium',
    tags: ['design', 'marketing'],
    createdAt: now - 14 * day,
    updatedAt: now - 11 * day,
  },
  // Chris Anderson
  {
    id: 'task-024',
    title: 'API rate limiting',
    description: 'Implement throttling for public APIs',
    assignedTo: 'emp-009',
    assignedBy: 'manager-001',
    deadline: now - 8 * day,
    status: 'overdue',
    estimatedHours: 10,
    priority: 'high',
    tags: ['backend', 'security'],
    createdAt: now - 12 * day,
    updatedAt: now - 9 * day,
  },
  // Rachel White
  {
    id: 'task-025',
    title: 'Load testing report',
    description: 'Performance testing for new release',
    assignedTo: 'emp-010',
    assignedBy: 'manager-001',
    deadline: now - 9 * day,
    completedAt: now - 10 * day,
    status: 'completed',
    estimatedHours: 12,
    actualHours: 11,
    priority: 'high',
    tags: ['qa', 'performance'],
    createdAt: now - 13 * day,
    updatedAt: now - 10 * day,
  },
  {
    id: 'task-026',
    title: 'QA process documentation',
    description: 'Document test procedures',
    assignedTo: 'emp-010',
    assignedBy: 'manager-001',
    deadline: now - 12 * day,
    completedAt: now - 13 * day,
    status: 'completed',
    estimatedHours: 8,
    actualHours: 7,
    priority: 'low',
    tags: ['qa', 'documentation'],
    createdAt: now - 14 * day,
    updatedAt: now - 13 * day,
  },

  // ============ DAYS 15-30 (30 days filter only) ============
  // John Smith - Older tasks
  {
    id: 'task-027',
    title: 'Initial dashboard implementation',
    description: 'Build main dashboard layout',
    assignedTo: 'emp-001',
    assignedBy: 'manager-001',
    deadline: now - 18 * day,
    completedAt: now - 19 * day,
    status: 'completed',
    estimatedHours: 24,
    actualHours: 22,
    priority: 'high',
    tags: ['ui', 'dashboard'],
    createdAt: now - 25 * day,
    updatedAt: now - 19 * day,
  },
  {
    id: 'task-028',
    title: 'Setup project structure',
    description: 'Initialize React project with TypeScript',
    assignedTo: 'emp-001',
    assignedBy: 'manager-001',
    deadline: now - 25 * day,
    completedAt: now - 26 * day,
    status: 'completed',
    estimatedHours: 8,
    actualHours: 6,
    priority: 'high',
    tags: ['setup', 'frontend'],
    createdAt: now - 28 * day,
    updatedAt: now - 26 * day,
  },
  // Sarah Johnson - Older
  {
    id: 'task-029',
    title: 'User API endpoints',
    description: 'CRUD operations for users',
    assignedTo: 'emp-002',
    assignedBy: 'manager-001',
    deadline: now - 20 * day,
    completedAt: now - 18 * day,
    status: 'completed',
    estimatedHours: 16,
    actualHours: 24,
    priority: 'high',
    tags: ['api', 'backend'],
    createdAt: now - 27 * day,
    updatedAt: now - 18 * day,
  },
  {
    id: 'task-030',
    title: 'Database schema design',
    description: 'Design initial database structure',
    assignedTo: 'emp-002',
    assignedBy: 'manager-001',
    deadline: now - 24 * day,
    completedAt: now - 25 * day,
    status: 'completed',
    estimatedHours: 12,
    actualHours: 14,
    priority: 'high',
    tags: ['database', 'design'],
    createdAt: now - 29 * day,
    updatedAt: now - 25 * day,
  },
  // Mike Wilson - Older
  {
    id: 'task-031',
    title: 'Initial wireframes',
    description: 'Create wireframes for all screens',
    assignedTo: 'emp-003',
    assignedBy: 'manager-002',
    deadline: now - 22 * day,
    completedAt: now - 23 * day,
    status: 'completed',
    estimatedHours: 20,
    actualHours: 18,
    priority: 'high',
    tags: ['design', 'wireframe'],
    createdAt: now - 28 * day,
    updatedAt: now - 23 * day,
  },
  {
    id: 'task-032',
    title: 'Design system setup',
    description: 'Create component library in Figma',
    assignedTo: 'emp-003',
    assignedBy: 'manager-002',
    deadline: now - 18 * day,
    completedAt: now - 19 * day,
    status: 'completed',
    estimatedHours: 24,
    actualHours: 26,
    priority: 'high',
    tags: ['design', 'system'],
    createdAt: now - 26 * day,
    updatedAt: now - 19 * day,
  },
  // Emily Davis - Older
  {
    id: 'task-033',
    title: 'Auth system implementation',
    description: 'JWT authentication with refresh tokens',
    assignedTo: 'emp-004',
    assignedBy: 'manager-001',
    deadline: now - 20 * day,
    completedAt: now - 21 * day,
    status: 'completed',
    estimatedHours: 20,
    actualHours: 18,
    priority: 'high',
    tags: ['backend', 'auth'],
    createdAt: now - 27 * day,
    updatedAt: now - 21 * day,
  },
  {
    id: 'task-034',
    title: 'API documentation',
    description: 'Setup Swagger/OpenAPI docs',
    assignedTo: 'emp-004',
    assignedBy: 'manager-001',
    deadline: now - 16 * day,
    completedAt: now - 17 * day,
    status: 'completed',
    estimatedHours: 8,
    actualHours: 6,
    priority: 'medium',
    tags: ['documentation', 'api'],
    createdAt: now - 22 * day,
    updatedAt: now - 17 * day,
  },
  // Alex Brown - Older (some completed here)
  {
    id: 'task-035',
    title: 'Test plan creation',
    description: 'Define testing strategy',
    assignedTo: 'emp-005',
    assignedBy: 'manager-001',
    deadline: now - 22 * day,
    completedAt: now - 23 * day,
    status: 'completed',
    estimatedHours: 12,
    actualHours: 14,
    priority: 'medium',
    tags: ['qa', 'planning'],
    createdAt: now - 28 * day,
    updatedAt: now - 23 * day,
  },
  {
    id: 'task-036',
    title: 'Setup test environment',
    description: 'Configure Jest and testing library',
    assignedTo: 'emp-005',
    assignedBy: 'manager-001',
    deadline: now - 18 * day,
    completedAt: now - 19 * day,
    status: 'completed',
    estimatedHours: 6,
    actualHours: 8,
    priority: 'medium',
    tags: ['testing', 'setup'],
    createdAt: now - 24 * day,
    updatedAt: now - 19 * day,
  },
  // Jessica Martinez - Older
  {
    id: 'task-037',
    title: 'CI/CD pipeline setup',
    description: 'Configure GitHub Actions',
    assignedTo: 'emp-006',
    assignedBy: 'manager-001',
    deadline: now - 20 * day,
    completedAt: now - 21 * day,
    status: 'completed',
    estimatedHours: 16,
    actualHours: 14,
    priority: 'high',
    tags: ['devops', 'ci-cd'],
    createdAt: now - 26 * day,
    updatedAt: now - 21 * day,
  },
  {
    id: 'task-038',
    title: 'AWS infrastructure',
    description: 'Setup EC2, RDS, and S3',
    assignedTo: 'emp-006',
    assignedBy: 'manager-001',
    deadline: now - 24 * day,
    completedAt: now - 25 * day,
    status: 'completed',
    estimatedHours: 20,
    actualHours: 18,
    priority: 'high',
    tags: ['devops', 'aws'],
    createdAt: now - 29 * day,
    updatedAt: now - 25 * day,
  },
  // David Lee - Older
  {
    id: 'task-039',
    title: 'Mobile app setup',
    description: 'Initialize React Native project',
    assignedTo: 'emp-007',
    assignedBy: 'manager-001',
    deadline: now - 22 * day,
    completedAt: now - 23 * day,
    status: 'completed',
    estimatedHours: 8,
    actualHours: 6,
    priority: 'high',
    tags: ['mobile', 'setup'],
    createdAt: now - 27 * day,
    updatedAt: now - 23 * day,
  },
  {
    id: 'task-040',
    title: 'Basic mobile navigation',
    description: 'Implement tab and stack navigation',
    assignedTo: 'emp-007',
    assignedBy: 'manager-001',
    deadline: now - 18 * day,
    completedAt: now - 19 * day,
    status: 'completed',
    estimatedHours: 12,
    actualHours: 10,
    priority: 'medium',
    tags: ['mobile', 'navigation'],
    createdAt: now - 24 * day,
    updatedAt: now - 19 * day,
  },
  // Amanda Taylor - Older
  {
    id: 'task-041',
    title: 'Logo design',
    description: 'Create company logo variants',
    assignedTo: 'emp-008',
    assignedBy: 'manager-002',
    deadline: now - 24 * day,
    completedAt: now - 25 * day,
    status: 'completed',
    estimatedHours: 16,
    actualHours: 18,
    priority: 'high',
    tags: ['design', 'branding'],
    createdAt: now - 29 * day,
    updatedAt: now - 25 * day,
  },
  {
    id: 'task-042',
    title: 'Social media assets',
    description: 'Create profile images and covers',
    assignedTo: 'emp-008',
    assignedBy: 'manager-002',
    deadline: now - 20 * day,
    completedAt: now - 21 * day,
    status: 'completed',
    estimatedHours: 8,
    actualHours: 7,
    priority: 'low',
    tags: ['design', 'social'],
    createdAt: now - 25 * day,
    updatedAt: now - 21 * day,
  },
  // Chris Anderson - Older
  {
    id: 'task-043',
    title: 'Product API endpoints',
    description: 'CRUD for products',
    assignedTo: 'emp-009',
    assignedBy: 'manager-001',
    deadline: now - 18 * day,
    completedAt: now - 17 * day,
    status: 'completed',
    estimatedHours: 16,
    actualHours: 20,
    priority: 'high',
    tags: ['api', 'backend'],
    createdAt: now - 25 * day,
    updatedAt: now - 17 * day,
  },
  {
    id: 'task-044',
    title: 'Order processing logic',
    description: 'Implement order workflow',
    assignedTo: 'emp-009',
    assignedBy: 'manager-001',
    deadline: now - 22 * day,
    completedAt: now - 21 * day,
    status: 'completed',
    estimatedHours: 20,
    actualHours: 24,
    priority: 'high',
    tags: ['backend', 'orders'],
    createdAt: now - 28 * day,
    updatedAt: now - 21 * day,
  },
  // Rachel White - Older
  {
    id: 'task-045',
    title: 'Initial test cases',
    description: 'Write tests for core modules',
    assignedTo: 'emp-010',
    assignedBy: 'manager-001',
    deadline: now - 20 * day,
    completedAt: now - 21 * day,
    status: 'completed',
    estimatedHours: 16,
    actualHours: 14,
    priority: 'medium',
    tags: ['qa', 'testing'],
    createdAt: now - 26 * day,
    updatedAt: now - 21 * day,
  },
  {
    id: 'task-046',
    title: 'Bug tracking setup',
    description: 'Configure Jira project',
    assignedTo: 'emp-010',
    assignedBy: 'manager-001',
    deadline: now - 25 * day,
    completedAt: now - 26 * day,
    status: 'completed',
    estimatedHours: 4,
    actualHours: 3,
    priority: 'medium',
    tags: ['qa', 'tools'],
    createdAt: now - 28 * day,
    updatedAt: now - 26 * day,
  },
  // Additional pending tasks for variety
  {
    id: 'task-047',
    title: 'Performance optimization',
    description: 'Optimize bundle size',
    assignedTo: 'emp-001',
    assignedBy: 'manager-001',
    deadline: now + 3 * day,
    status: 'pending',
    estimatedHours: 12,
    priority: 'medium',
    tags: ['performance', 'frontend'],
    createdAt: now - 1 * day,
    updatedAt: now - 1 * day,
  },
  {
    id: 'task-048',
    title: 'User feedback form',
    description: 'Implement feedback collection',
    assignedTo: 'emp-003',
    assignedBy: 'manager-002',
    deadline: now + 5 * day,
    status: 'pending',
    estimatedHours: 8,
    priority: 'low',
    tags: ['design', 'feedback'],
    createdAt: now - 2 * day,
    updatedAt: now - 2 * day,
  },
];

// Mock Chat Messages - Spread across 30 days
export const mockChatMessages: EmployeeChatMessage[] = [
  // ============ LAST 7 DAYS ============
  // John Smith - work focused
  {
    id: 'msg-001',
    employeeId: 'emp-001',
    content: 'Fixed the navigation bug, PR is ready for review',
    timestamp: now - 1 * day,
    chatType: 'team',
    participantIds: ['emp-001', 'emp-004'],
    participantNames: ['John Smith', 'Emily Davis'],
  },
  {
    id: 'msg-002',
    employeeId: 'emp-001',
    content: 'Dashboard update is complete, deployed to staging',
    timestamp: now - 2 * day,
    chatType: 'team',
    participantIds: ['emp-001', 'manager-001'],
    participantNames: ['John Smith', 'Manager'],
  },
  {
    id: 'msg-003',
    employeeId: 'emp-001',
    content: 'Working on the performance task now',
    timestamp: now - 3 * day,
    chatType: 'team',
    participantIds: ['emp-001', 'emp-004'],
    participantNames: ['John Smith', 'Emily Davis'],
  },
  // Sarah Johnson - mixed with non-work
  {
    id: 'msg-004',
    employeeId: 'emp-002',
    content: 'Did you watch the game last night? Crazy ending!',
    timestamp: now - 1 * day,
    chatType: 'team',
    participantIds: ['emp-002', 'emp-005'],
    participantNames: ['Sarah Johnson', 'Alex Brown'],
  },
  {
    id: 'msg-005',
    employeeId: 'emp-002',
    content: 'Still working on the API optimization, hitting some issues',
    timestamp: now - 2 * day,
    chatType: 'team',
    participantIds: ['emp-002', 'manager-001'],
    participantNames: ['Sarah Johnson', 'Manager'],
  },
  {
    id: 'msg-006',
    employeeId: 'emp-002',
    content: 'Anyone want to grab lunch? Found a new place',
    timestamp: now - 3 * day,
    chatType: 'team',
    participantIds: ['emp-002', 'emp-005', 'emp-009'],
    participantNames: ['Sarah Johnson', 'Alex Brown', 'Chris Anderson'],
  },
  {
    id: 'msg-007',
    employeeId: 'emp-002',
    content: 'Check out this funny video I found',
    timestamp: now - 4 * day,
    chatType: 'team',
    participantIds: ['emp-002', 'emp-005'],
    participantNames: ['Sarah Johnson', 'Alex Brown'],
  },
  // Mike Wilson
  {
    id: 'msg-008',
    employeeId: 'emp-003',
    content: 'Homepage mockup is 50% done, will share preview today',
    timestamp: now - 1 * day,
    chatType: 'team',
    participantIds: ['emp-003', 'manager-002'],
    participantNames: ['Mike Wilson', 'Manager'],
  },
  {
    id: 'msg-009',
    employeeId: 'emp-003',
    content: 'Can we sync on the color palette choices?',
    timestamp: now - 3 * day,
    chatType: 'team',
    participantIds: ['emp-003', 'emp-008'],
    participantNames: ['Mike Wilson', 'Amanda Taylor'],
  },
  // Emily Davis - productive
  {
    id: 'msg-010',
    employeeId: 'emp-004',
    content: 'Caching layer is live, seeing 40% performance improvement',
    timestamp: now - 2 * day,
    chatType: 'team',
    participantIds: ['emp-004', 'manager-001'],
    participantNames: ['Emily Davis', 'Manager'],
  },
  {
    id: 'msg-011',
    employeeId: 'emp-004',
    content: 'Reviewed the payment PR, left some suggestions',
    timestamp: now - 1 * day,
    chatType: 'team',
    participantIds: ['emp-004', 'emp-002'],
    participantNames: ['Emily Davis', 'Sarah Johnson'],
  },
  {
    id: 'msg-012',
    employeeId: 'emp-004',
    content: 'Happy to help with the API issues if needed',
    timestamp: now - 3 * day,
    chatType: 'team',
    participantIds: ['emp-004', 'emp-002'],
    participantNames: ['Emily Davis', 'Sarah Johnson'],
  },
  // Alex Brown - excuses
  {
    id: 'msg-013',
    employeeId: 'emp-005',
    content: 'My laptop is running slow today, IT is looking at it',
    timestamp: now - 2 * day,
    chatType: 'team',
    participantIds: ['emp-005', 'manager-001'],
    participantNames: ['Alex Brown', 'Manager'],
  },
  {
    id: 'msg-014',
    employeeId: 'emp-005',
    content: 'Did anyone see the new Marvel trailer?',
    timestamp: now - 1 * day,
    chatType: 'team',
    participantIds: ['emp-005', 'emp-002'],
    participantNames: ['Alex Brown', 'Sarah Johnson'],
  },
  {
    id: 'msg-015',
    employeeId: 'emp-005',
    content: 'Network issues again, cant push code',
    timestamp: now - 4 * day,
    chatType: 'team',
    participantIds: ['emp-005', 'manager-001'],
    participantNames: ['Alex Brown', 'Manager'],
  },
  // Jessica Martinez
  {
    id: 'msg-016',
    employeeId: 'emp-006',
    content: 'Staging environment is ready, sending credentials',
    timestamp: now - 1 * day,
    chatType: 'team',
    participantIds: ['emp-006', 'emp-004'],
    participantNames: ['Jessica Martinez', 'Emily Davis'],
  },
  {
    id: 'msg-017',
    employeeId: 'emp-006',
    content: 'Monitoring dashboards are set up in Grafana',
    timestamp: now - 3 * day,
    chatType: 'team',
    participantIds: ['emp-006', 'manager-001'],
    participantNames: ['Jessica Martinez', 'Manager'],
  },
  // David Lee
  {
    id: 'msg-018',
    employeeId: 'emp-007',
    content: 'Found the iOS crash issue - race condition on startup',
    timestamp: now - 2 * day,
    chatType: 'team',
    participantIds: ['emp-007', 'emp-010'],
    participantNames: ['David Lee', 'Rachel White'],
  },
  {
    id: 'msg-019',
    employeeId: 'emp-007',
    content: 'Working on the fix, should have it today',
    timestamp: now - 1 * day,
    chatType: 'team',
    participantIds: ['emp-007', 'manager-001'],
    participantNames: ['David Lee', 'Manager'],
  },
  // Amanda Taylor
  {
    id: 'msg-020',
    employeeId: 'emp-008',
    content: 'Email templates are looking great, sharing preview',
    timestamp: now - 2 * day,
    chatType: 'team',
    participantIds: ['emp-008', 'manager-002'],
    participantNames: ['Amanda Taylor', 'Manager'],
  },
  // Chris Anderson
  {
    id: 'msg-021',
    employeeId: 'emp-009',
    content: 'VPN is acting up, working on it',
    timestamp: now - 1 * day,
    chatType: 'team',
    participantIds: ['emp-009', 'emp-006'],
    participantNames: ['Chris Anderson', 'Jessica Martinez'],
  },
  // Rachel White
  {
    id: 'msg-022',
    employeeId: 'emp-010',
    content: 'Security audit is complete, no critical issues found',
    timestamp: now - 1 * day,
    chatType: 'team',
    participantIds: ['emp-010', 'manager-001'],
    participantNames: ['Rachel White', 'Manager'],
  },
  {
    id: 'msg-023',
    employeeId: 'emp-010',
    content: 'Starting regression testing now',
    timestamp: now - 2 * day,
    chatType: 'team',
    participantIds: ['emp-010', 'emp-005'],
    participantNames: ['Rachel White', 'Alex Brown'],
  },

  // ============ DAYS 8-14 ============
  {
    id: 'msg-024',
    employeeId: 'emp-001',
    content: 'Dark mode implementation is done!',
    timestamp: now - 9 * day,
    chatType: 'team',
    participantIds: ['emp-001', 'manager-001'],
    participantNames: ['John Smith', 'Manager'],
  },
  {
    id: 'msg-025',
    employeeId: 'emp-001',
    content: 'Form refactoring PR is ready',
    timestamp: now - 11 * day,
    chatType: 'team',
    participantIds: ['emp-001', 'emp-004'],
    participantNames: ['John Smith', 'Emily Davis'],
  },
  {
    id: 'msg-026',
    employeeId: 'emp-002',
    content: 'Migration script finally working after many issues',
    timestamp: now - 9 * day,
    chatType: 'team',
    participantIds: ['emp-002', 'manager-001'],
    participantNames: ['Sarah Johnson', 'Manager'],
  },
  {
    id: 'msg-027',
    employeeId: 'emp-002',
    content: 'Going to lunch early today, back in an hour',
    timestamp: now - 10 * day,
    chatType: 'team',
    participantIds: ['emp-002', 'emp-005'],
    participantNames: ['Sarah Johnson', 'Alex Brown'],
  },
  {
    id: 'msg-028',
    employeeId: 'emp-003',
    content: 'App icons uploaded to the shared drive',
    timestamp: now - 8 * day,
    chatType: 'team',
    participantIds: ['emp-003', 'emp-007'],
    participantNames: ['Mike Wilson', 'David Lee'],
  },
  {
    id: 'msg-029',
    employeeId: 'emp-003',
    content: 'Brand guidelines doc is updated',
    timestamp: now - 11 * day,
    chatType: 'team',
    participantIds: ['emp-003', 'manager-002'],
    participantNames: ['Mike Wilson', 'Manager'],
  },
  {
    id: 'msg-030',
    employeeId: 'emp-004',
    content: 'Notification system tested and deployed',
    timestamp: now - 10 * day,
    chatType: 'team',
    participantIds: ['emp-004', 'emp-006'],
    participantNames: ['Emily Davis', 'Jessica Martinez'],
  },
  {
    id: 'msg-031',
    employeeId: 'emp-005',
    content: 'Test automation setup is blocked by permissions',
    timestamp: now - 11 * day,
    chatType: 'team',
    participantIds: ['emp-005', 'manager-001'],
    participantNames: ['Alex Brown', 'Manager'],
  },
  {
    id: 'msg-032',
    employeeId: 'emp-006',
    content: 'K8s cluster is production ready',
    timestamp: now - 9 * day,
    chatType: 'team',
    participantIds: ['emp-006', 'manager-001'],
    participantNames: ['Jessica Martinez', 'Manager'],
  },
  {
    id: 'msg-033',
    employeeId: 'emp-006',
    content: 'PagerDuty alerts configured and tested',
    timestamp: now - 12 * day,
    chatType: 'team',
    participantIds: ['emp-006', 'emp-010'],
    participantNames: ['Jessica Martinez', 'Rachel White'],
  },
  {
    id: 'msg-034',
    employeeId: 'emp-007',
    content: 'Android notifications working perfectly',
    timestamp: now - 10 * day,
    chatType: 'team',
    participantIds: ['emp-007', 'manager-001'],
    participantNames: ['David Lee', 'Manager'],
  },
  {
    id: 'msg-035',
    employeeId: 'emp-008',
    content: 'Banner designs approved by marketing',
    timestamp: now - 11 * day,
    chatType: 'team',
    participantIds: ['emp-008', 'manager-002'],
    participantNames: ['Amanda Taylor', 'Manager'],
  },
  {
    id: 'msg-036',
    employeeId: 'emp-009',
    content: 'Rate limiting is more complex than expected',
    timestamp: now - 9 * day,
    chatType: 'team',
    participantIds: ['emp-009', 'manager-001'],
    participantNames: ['Chris Anderson', 'Manager'],
  },
  {
    id: 'msg-037',
    employeeId: 'emp-010',
    content: 'Load testing report is ready for review',
    timestamp: now - 10 * day,
    chatType: 'team',
    participantIds: ['emp-010', 'manager-001'],
    participantNames: ['Rachel White', 'Manager'],
  },
  {
    id: 'msg-038',
    employeeId: 'emp-010',
    content: 'QA documentation uploaded to Confluence',
    timestamp: now - 13 * day,
    chatType: 'team',
    participantIds: ['emp-010', 'emp-005'],
    participantNames: ['Rachel White', 'Alex Brown'],
  },

  // ============ DAYS 15-30 ============
  {
    id: 'msg-039',
    employeeId: 'emp-001',
    content: 'Dashboard layout is complete, ready for content',
    timestamp: now - 19 * day,
    chatType: 'team',
    participantIds: ['emp-001', 'manager-001'],
    participantNames: ['John Smith', 'Manager'],
  },
  {
    id: 'msg-040',
    employeeId: 'emp-001',
    content: 'Project structure is set up with all configs',
    timestamp: now - 26 * day,
    chatType: 'team',
    participantIds: ['emp-001', 'emp-004'],
    participantNames: ['John Smith', 'Emily Davis'],
  },
  {
    id: 'msg-041',
    employeeId: 'emp-002',
    content: 'User API is done, took longer than expected',
    timestamp: now - 18 * day,
    chatType: 'team',
    participantIds: ['emp-002', 'manager-001'],
    participantNames: ['Sarah Johnson', 'Manager'],
  },
  {
    id: 'msg-042',
    employeeId: 'emp-002',
    content: 'Database schema finalized and reviewed',
    timestamp: now - 25 * day,
    chatType: 'team',
    participantIds: ['emp-002', 'emp-004'],
    participantNames: ['Sarah Johnson', 'Emily Davis'],
  },
  {
    id: 'msg-043',
    employeeId: 'emp-003',
    content: 'All wireframes are complete and approved',
    timestamp: now - 23 * day,
    chatType: 'team',
    participantIds: ['emp-003', 'manager-002'],
    participantNames: ['Mike Wilson', 'Manager'],
  },
  {
    id: 'msg-044',
    employeeId: 'emp-003',
    content: 'Design system is ready in Figma',
    timestamp: now - 19 * day,
    chatType: 'team',
    participantIds: ['emp-003', 'emp-001'],
    participantNames: ['Mike Wilson', 'John Smith'],
  },
  {
    id: 'msg-045',
    employeeId: 'emp-004',
    content: 'Auth system is fully implemented and tested',
    timestamp: now - 21 * day,
    chatType: 'team',
    participantIds: ['emp-004', 'manager-001'],
    participantNames: ['Emily Davis', 'Manager'],
  },
  {
    id: 'msg-046',
    employeeId: 'emp-004',
    content: 'Swagger docs are live at /api-docs',
    timestamp: now - 17 * day,
    chatType: 'team',
    participantIds: ['emp-004', 'emp-002'],
    participantNames: ['Emily Davis', 'Sarah Johnson'],
  },
  {
    id: 'msg-047',
    employeeId: 'emp-005',
    content: 'Test plan document is ready for review',
    timestamp: now - 23 * day,
    chatType: 'team',
    participantIds: ['emp-005', 'emp-010'],
    participantNames: ['Alex Brown', 'Rachel White'],
  },
  {
    id: 'msg-048',
    employeeId: 'emp-005',
    content: 'Jest and testing library are configured',
    timestamp: now - 19 * day,
    chatType: 'team',
    participantIds: ['emp-005', 'manager-001'],
    participantNames: ['Alex Brown', 'Manager'],
  },
  {
    id: 'msg-049',
    employeeId: 'emp-006',
    content: 'GitHub Actions pipeline is green',
    timestamp: now - 21 * day,
    chatType: 'team',
    participantIds: ['emp-006', 'manager-001'],
    participantNames: ['Jessica Martinez', 'Manager'],
  },
  {
    id: 'msg-050',
    employeeId: 'emp-006',
    content: 'AWS infrastructure is provisioned and secured',
    timestamp: now - 25 * day,
    chatType: 'team',
    participantIds: ['emp-006', 'emp-004'],
    participantNames: ['Jessica Martinez', 'Emily Davis'],
  },
  {
    id: 'msg-051',
    employeeId: 'emp-007',
    content: 'React Native project initialized with navigation',
    timestamp: now - 23 * day,
    chatType: 'team',
    participantIds: ['emp-007', 'manager-001'],
    participantNames: ['David Lee', 'Manager'],
  },
  {
    id: 'msg-052',
    employeeId: 'emp-007',
    content: 'Navigation structure is complete',
    timestamp: now - 19 * day,
    chatType: 'team',
    participantIds: ['emp-007', 'emp-003'],
    participantNames: ['David Lee', 'Mike Wilson'],
  },
  {
    id: 'msg-053',
    employeeId: 'emp-008',
    content: 'Logo variants are ready for brand kit',
    timestamp: now - 25 * day,
    chatType: 'team',
    participantIds: ['emp-008', 'manager-002'],
    participantNames: ['Amanda Taylor', 'Manager'],
  },
  {
    id: 'msg-054',
    employeeId: 'emp-008',
    content: 'Social media assets uploaded to Drive',
    timestamp: now - 21 * day,
    chatType: 'team',
    participantIds: ['emp-008', 'emp-003'],
    participantNames: ['Amanda Taylor', 'Mike Wilson'],
  },
  {
    id: 'msg-055',
    employeeId: 'emp-009',
    content: 'Product API endpoints are deployed',
    timestamp: now - 17 * day,
    chatType: 'team',
    participantIds: ['emp-009', 'emp-004'],
    participantNames: ['Chris Anderson', 'Emily Davis'],
  },
  {
    id: 'msg-056',
    employeeId: 'emp-009',
    content: 'Order workflow logic is implemented',
    timestamp: now - 21 * day,
    chatType: 'team',
    participantIds: ['emp-009', 'manager-001'],
    participantNames: ['Chris Anderson', 'Manager'],
  },
  {
    id: 'msg-057',
    employeeId: 'emp-010',
    content: 'Core module tests are all passing',
    timestamp: now - 21 * day,
    chatType: 'team',
    participantIds: ['emp-010', 'emp-004'],
    participantNames: ['Rachel White', 'Emily Davis'],
  },
  {
    id: 'msg-058',
    employeeId: 'emp-010',
    content: 'Jira project is configured with workflows',
    timestamp: now - 26 * day,
    chatType: 'team',
    participantIds: ['emp-010', 'manager-001'],
    participantNames: ['Rachel White', 'Manager'],
  },
  // Extra non-work messages in older period
  {
    id: 'msg-059',
    employeeId: 'emp-002',
    content: 'Team lunch tomorrow? That new pizza place looks good',
    timestamp: now - 16 * day,
    chatType: 'team',
    participantIds: ['emp-002', 'emp-005', 'emp-009'],
    participantNames: ['Sarah Johnson', 'Alex Brown', 'Chris Anderson'],
  },
  {
    id: 'msg-060',
    employeeId: 'emp-005',
    content: 'Anyone watching the game this weekend?',
    timestamp: now - 20 * day,
    chatType: 'team',
    participantIds: ['emp-005', 'emp-002'],
    participantNames: ['Alex Brown', 'Sarah Johnson'],
  },
];

// Mock Notifications - Spread across time periods
export const mockNotifications: PerformanceNotification[] = [
  // Recent (7 days)
  {
    id: 'notif-001',
    employeeId: 'emp-002',
    employeeName: 'Sarah Johnson',
    type: 'deadline_missed',
    title: 'Deadline Missed',
    message: 'API endpoint optimization is overdue by 2 days',
    severity: 'critical',
    read: false,
    createdAt: now - 2 * day,
    relatedTaskId: 'task-003',
  },
  {
    id: 'notif-002',
    employeeId: 'emp-005',
    employeeName: 'Alex Brown',
    type: 'deadline_missed',
    title: 'Deadline Missed',
    message: 'Unit tests for auth overdue by 3 days',
    severity: 'critical',
    read: false,
    createdAt: now - 3 * day,
    relatedTaskId: 'task-007',
  },
  {
    id: 'notif-003',
    employeeId: 'emp-007',
    employeeName: 'David Lee',
    type: 'deadline_missed',
    title: 'Urgent Bug Overdue',
    message: 'iOS crash fix is overdue',
    severity: 'critical',
    read: false,
    createdAt: now - 1 * day,
    relatedTaskId: 'task-009',
  },
  {
    id: 'notif-004',
    employeeId: 'emp-004',
    employeeName: 'Emily Davis',
    type: 'analysis_complete',
    title: 'Excellent Performance',
    message: 'All tasks completed ahead of schedule',
    severity: 'info',
    read: true,
    createdAt: now - 2 * day,
  },
  // Medium term (8-14 days)
  {
    id: 'notif-005',
    employeeId: 'emp-002',
    employeeName: 'Sarah Johnson',
    type: 'low_performance',
    title: 'Performance Warning',
    message: 'Database migration took 3x longer than estimated',
    severity: 'warning',
    read: true,
    createdAt: now - 9 * day,
    relatedTaskId: 'task-014',
  },
  {
    id: 'notif-006',
    employeeId: 'emp-006',
    employeeName: 'Jessica Martinez',
    type: 'analysis_complete',
    title: 'Good Performance',
    message: 'K8s setup completed on schedule',
    severity: 'info',
    read: true,
    createdAt: now - 9 * day,
  },
  {
    id: 'notif-007',
    employeeId: 'emp-009',
    employeeName: 'Chris Anderson',
    type: 'deadline_missed',
    title: 'Deadline Missed',
    message: 'API rate limiting is overdue',
    severity: 'critical',
    read: false,
    createdAt: now - 8 * day,
    relatedTaskId: 'task-024',
  },
  // Older (15-30 days)
  {
    id: 'notif-008',
    employeeId: 'emp-010',
    employeeName: 'Rachel White',
    type: 'analysis_complete',
    title: 'Excellent Performance',
    message: 'All QA tasks completed ahead of schedule',
    severity: 'info',
    read: true,
    createdAt: now - 21 * day,
  },
];

// Helper function to get tasks for an employee within a date range
export function getEmployeeTasks(employeeId: string, startDate: number, endDate: number): Task[] {
  return mockTasks.filter(task =>
    task.assignedTo === employeeId &&
    task.createdAt >= startDate &&
    task.createdAt <= endDate
  );
}

// Helper function to get messages for an employee within a date range
export function getEmployeeMessages(employeeId: string, startDate: number, endDate: number): EmployeeChatMessage[] {
  return mockChatMessages.filter(msg =>
    msg.employeeId === employeeId &&
    msg.timestamp >= startDate &&
    msg.timestamp <= endDate
  );
}

// Helper to get all employees
export function getAllEmployees(): Employee[] {
  return mockEmployees;
}

// Helper to get employee by ID
export function getEmployeeById(id: string): Employee | undefined {
  return mockEmployees.find(emp => emp.id === id);
}

// Helper to get task by ID
export function getTaskById(id: string): Task | undefined {
  return mockTasks.find(task => task.id === id);
}

// Helper to get all notifications
export function getNotifications(): PerformanceNotification[] {
  return mockNotifications;
}
